/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "UART_1.h"
#include "Pin_Button1_aliases.h"
#include "Pin_Button1.h"
#include "Pin_Button2_aliases.h"
#include "Pin_Button2.h"
#include "isr_Button.h"
#include "SEVENSEG_REG.h"
#include "SEVSEG_A_aliases.h"
#include "SEVSEG_A.h"
#include "SEVSEG_B_aliases.h"
#include "SEVSEG_B.h"
#include "SEVSEG_C_aliases.h"
#include "SEVSEG_C.h"
#include "SEVSEG_D_aliases.h"
#include "SEVSEG_D.h"
#include "SEVSEG_E_aliases.h"
#include "SEVSEG_E.h"
#include "SEVSEG_F_aliases.h"
#include "SEVSEG_F.h"
#include "SEVSEG_G_aliases.h"
#include "SEVSEG_G.h"
#include "SEVSEG_DP_aliases.h"
#include "SEVSEG_DP.h"
#include "Pin_SEVENSEL_aliases.h"
#include "Pin_SEVENSEL.h"
#include "PWM_LED_RED.h"
#include "PWM_LED_GREEN.h"
#include "PWM_LED_YELLOW.h"
#include "Clock_PWM.h"
#include "Pin_LED_RED_aliases.h"
#include "Pin_LED_RED.h"
#include "Pin_LED_GREEN_aliases.h"
#include "Pin_LED_GREEN.h"
#include "Pin_LED_YELLOW_aliases.h"
#include "Pin_LED_YELLOW.h"
#include "Pin_RGB_RED_aliases.h"
#include "Pin_RGB_RED.h"
#include "Pin_RGB_GREEN_aliases.h"
#include "Pin_RGB_GREEN.h"
#include "Pin_RGB_BLUE_aliases.h"
#include "Pin_RGB_BLUE.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

